import { LitElement } from "lit";
import { PageController } from "@open-cells/page-controller";
export declare class BoardDetailPage extends LitElement {
  pageController: PageController;
  params: Record<string, string>;
  private detail;
  private error;
  private expandedColumnId;
  private dragOverStateId;
  private newColumnTitle;
  private newColumnColor;
  private showColumnForm;
  private editingStateId;
  private editingStateTitle;
  private editingStateColor;
  private showTaskModal;
  private modalTitle;
  private modalDescription;
  private modalError;
  private boundKeydown;
  static styles: import("lit").CSSResult;
  connectedCallback(): Promise<void>;
  disconnectedCallback(): void;
  onPageEnter(): Promise<void>;
  private loadBoard;
  private getMandatoryOrder;
  private getSortedStates;
  private getMaxTaskCount;
  private handleKeydown;
  private handleDragStart;
  private handleDragOver;
  private handleDragLeave;
  private handleDrop;
  private selectTask;
  private handleCreateState;
  private startEditState;
  private saveEditState;
  private cancelEditState;
  private handleDeleteState;
  private toggleColumn;
  private openTaskModal;
  private closeTaskModal;
  private handleModalCreate;
  private renderBar;
  private renderExpanded;
  render(): import("lit").TemplateResult<1>;
}
