import { LitElement } from "lit";
import { PageController } from "@open-cells/page-controller";
import "../../ui/components/done-stamp.js";
import "../../ui/components/activity-feed.js";
export declare class BoardDetailPage extends LitElement {
    pageController: PageController;
    params: Record<string, string>;
    private detail;
    private error;
    private expandedColumnId;
    private dragOverStateId;
    private newColumnTitle;
    private newColumnColor;
    private showColumnForm;
    private editingStateId;
    private editingStateTitle;
    private editingStateColor;
    private showTaskModal;
    private modalTitle;
    private modalDescription;
    private modalError;
    private editingBoardTitle;
    private editingBoardTitleValue;
    private showActivity;
    private boundKeydown;
    static styles: import("lit").CSSResult;
    connectedCallback(): void;
    disconnectedCallback(): void;
    onPageEnter(): Promise<void>;
    private getMandatoryOrder;
    private getSortedStates;
    private getMaxTaskCount;
    private loadBoard;
    private handleEditBoardTitle;
    private handleSaveBoardTitle;
    private handleCancelBoardTitle;
    private handleDeleteBoard;
    private handleKeydown;
    private toggleColumn;
    private handleDragStart;
    private handleDragOver;
    private handleDragLeave;
    private handleDrop;
    private selectTask;
    private handleCreateState;
    private startEditState;
    private saveEditState;
    private cancelEditState;
    private handleDeleteState;
    private canMoveState;
    private moveStateLeft;
    private moveStateRight;
    private openTaskModal;
    private closeTaskModal;
    private handleModalCreate;
    private renderTaskCard;
    private renderBar;
    private renderExpanded;
    render(): import("lit").TemplateResult<1>;
}
