import { LitElement } from "lit";
import { PageController } from "@open-cells/page-controller";
import "../../ui/components/wysiwyg-editor.js";
import "../../ui/components/done-stamp.js";
import "../../ui/components/not-now-stamp.js";
import "../../ui/components/step-checklist.js";
import "../../ui/components/attachment-list.js";
import "../../ui/components/state-selector.js";
import "../../ui/components/quick-actions.js";
import "../../ui/components/keycap.js";
import "../../ui/components/not-now-stamp.js";
export declare class TaskDetailPage extends LitElement {
  pageController: PageController;
  params: Record<string, string>;
  private task;
  private comments;
  private steps;
  private timeline;
  private historyShowAll;
  private states;
  private error;
  private editingTaskDesc;
  private editTitle;
  private editDueDate;
  private newCommentHtml;
  private editingCommentId;
  private editingCommentText;
  private boundKeydown;
  private get _isDone();
  private get _isNotNow();
  static styles: import("lit").CSSResult;
  connectedCallback(): void;
  disconnectedCallback(): void;
  onPageEnter(): Promise<void>;
  private _handleGlobalKeydown;
  private _loadTask;
  private goBack;
  private startEditTask;
  private cancelEditTask;
  private _handleCommentEditorChange;
  private saveEditTask;
  private markAsDone;
  private handleDeleteTask;
  private handleAttachTaskImage;
  private handleDetachTaskImage;
  private toggleGold;
  private togglePin;
  private handleStateChange;
  private handleAddComment;
  private startEditComment;
  private cancelEditComment;
  private saveEditComment;
  private handleDeleteComment;
  private handleAttachCommentImage;
  private handleDetachCommentImage;
  private handleStepAdd;
  private handleStepToggle;
  private handleStepDelete;
  private _formatDate;
  private _stampDate;
  private _relativeTime;
  private _inactiveDays;
  render(): import("lit").TemplateResult<1>;
}
